language: node_js
node_js:
- '6'
sudo: false
cache:
  directories:
  - node_modules
before_script:
- npm install -g codeclimate-test-reporter
after_success:
- codeclimate-test-reporter < coverage/lcov.info
env:
  global:
    secure: adBKlbkP6T15YafhJCB5jIPKZr87l9Nz5+HFqzGUkbLkGfv/HI94bkCOORu3Qo3ZC93eSTLvSyI4Bf0KduKGQ7+8Wbb2Ze2d6MnthiCdfh6BzYEybmZ+uNpSEBa0C5dTKszGGWkoTOgfNhaLX0GklFsqF5yRkrA9B14ibyBioL3Uo0Ot32qtXE1RdoLoNuY/YsYHpB+hBn7x1wS3TVIsH+rtkF27m4I+YvVEMLQGj0ayaET/rmyEstYaPVimQRzFrMunKnLPhDGXDV3+ocLe1aDZy2BbETLYhg0OxOUtxtKCawrezOA/vbgW85KDYS5mcbZ2GOppzn5kikA69G659SvrTK8hgT67TLsAgMk/Yt9xAcy0phGjwDgXjng0LijJo2ZO8m6kxgsaN3inVbSt0hYsaaAFZOMeIhbHKLYauz9toAtRAKsmTtoTMH6HarMmzZM4T63CVSJXe9W/hSK8udtDx5ArI2HEcde8DzYZVvQoEkZLvmWOqfq/7uZ9QyvtOsrN5VvvGA+etvpzVr+1zbpAuaYs0D8v6/HBqcuh08d2soR/08iHsPmGK1B89tH25Ho/7TaBIshKFdO8znDiiCzTu91FY2R3WQD/Lp92SniFZBKNzn3WFaCh/JZkF9IPyQKhiToNXQEgI6mKyaZPmfyaYsADby5/AO0VpK7w7bU=
