language: node_js
node_js:
- '6'
sudo: false
cache:
  directories:
  - node_modules
before_script:
- npm install -g codeclimate-test-reporter
after_success:
- codeclimate-test-reporter < coverage/lcov.info
env:
  global:
    secure: JiamXzSDGvxtjKA8T6f95yGOj6+YLTqJJMCUYJ7LZ1KqOKSoHKQa+OXXS4/dmrjVInJS1jvF6niSZjgOLwv/ek00YoJmA4WpfCxu0yb8odA7N7A6B5MHMfUmUGkbPYzIEPTeChrlXwp3/r/pBy7cx5efm8nEReDYN2XAPKMr6yy6tLhNCL85w4w+dxP31lBQZyKOELN7dPd8QO2hyTxTSVaWthaLQPZhzdITyaPcGOnvdu+/sHuKh0ubTLa4SlrPC9zsTPLlGM0D8h5YXTMUrev1fl51tInCiiA0g5SiCIrHHuMdCQgWidQjISq1pqCAqQmoILPy4bAHpBJXaFKW1ILl/vWflhllufVvagVtJOLxbUqmm4fvpRSsLSygZy/XyAHmeiiEZExZeFzaytUFeSxBdXkw+xM5twfuSLkswSxIrCmoJKm22JopLYQ10N23Rj2oAn+6Cu3G3Wk1ugBCVFFVjzVKVlJm3MoH+RNsJOXB5gzHPnRUYWCUDYuoWkGh46FAQD7RyEkOF4ss7tIVnIRmmfM9S6PPuKmT2U7t6SApmMoyDvCDef5mojHAZVOE6z3RYwgPfBCrdfuFlldlri7E+HS/2voS4rNhBk55SuLjOGiODHJcc4tQv1j7zbtstOF1i08go062wzisuknqRQGyQeFB+QDj/Ed0jnNBYpQ=
