language: node_js
node_js:
- '6'
sudo: false
cache:
  directories:
  - node_modules
before_script:
- npm install -g codeclimate-test-reporter
after_success:
- codeclimate-test-reporter < coverage/lcov.info
env:
  global:
  - secure: P/XXg4M47hEanEC65IdVwDQjaSK9Z28L+tV29rx0pb/gsM44I+yytMuJ6Sr6xstmCKS1tCzpVnE59W5lkNoKTjKLMoWvPk9SMUvPfg51Ip3NmWQqtDWQcsZoAw+uhDcksEI+7Vdq+6TrL+SMS7Gbs1CDr44AP8y001ESwfk9evq7wpuwEso0By0/69jHinplXcwnr6U9D4kS1UE8oRkEILfgl7KQLNk84WT2sSaWDzNbEidvHBRq+gle/kPvwt2FWO6J5dtfO2mKQHWvZ7XZM3Z6Qfzh/3pY+4xsp0kpNBa0aD8ojEnofRwggnIhoA3zY5lChak8WU8tU+qvnmADfvRi93/nRGNhoKrwum9S6CZHVEGCGC2+/WgvnGtjkE6fPT0u+MVZ4diFd6xx3mhq5Ur2AcBPSiBX4zheyabmFvkajOEmTG/pNxwR0xC8/4JO+wdHNIinBu/JttsNve5XP55PTxR+lgmTrBtmCZmcjk2V7gpgXuVLukFpzgb0E1fRmrugMLuqu0L8DyecqhfuG1gIHe2/av4hRt9PxBmEpSVhZiwzZW3w5P3auWiQbAwsyPBZBtm/xWQbivUtoC2yMmjm7W/7XxA28ewZv36bAtkPK3qyDvPlxQDABKVRnNmJh17ukOW31Fu4VFATrmB9S4Njcr8vPhBOQ+4XF4v7hs8=
  - secure: PnsLaTYRfNrm9C07AQtbWySxQ+FY+l49D9lsatPfsEX0lv0cIWwNF0FrNKZVGapo33p257OyKeLCuDXpD72oP2bDCx03q19B6G4csaOWstEnWo+Iufvoqrg/Mq8mfx0kp/StdoZyVKUfu9dlwlS3OhV9FFlN0SG3qXs8DPahTz/3GEhVtsUIbo+eyV9cG2/l2b5QtV1A3UqO0LhvJ5rCdFqXuhsveKyVxQYJEem1FWFWFDZ9Rrx8ygPeP8upJa1vJ4pS9QyaHwiuRn3vjjmhm8cy5QMh53ag8DQERq60ThaKtpLoUKCGcC2o4c0m8rrhYpfZ8fx6ktdOF2xJwmoERLWaXlqnRksTIb3M/TnwJuYoyrThLwHRalMci8VQISnABCi7QtWuE4Yf0UoAuBdNK/HrDLtEKl3AMNdu04T1rBiPpF9usNxJ0JnOWmQEt/0Hcf3y7MEclQOfFWOEozJT9EZsI2G96jz8SCPcoFwGZe0twjSYb7557LwGYykFbElds0SkxTR30dktEAUZfBKl/tKq6AhiInDzTskvDvnGyMhOVWkzCWeY68qyzoRUiSzA25vilCAM6Gl5PIrjz97s/2kJ9avhEZVKI3q8tI2MKRjXmoXR9K2sE3V2qIE2f2VZgskdWtYAGqQZt4FDsFIWCWgckNwB2sXt8S7Y3ki0LsY=
